package by.training.online_pharmacy.dao.impl.database;

import org.omg.PortableServer.ServantRetentionPolicy;
import org.openxmlformats.schemas.drawingml.x2006.chart.STErrBarType;

/**
 * Created by vladislav on 29.09.16.
 */
public class Constant {
    public static final String ANALGETIK = "Анальгетик";
    public static final String OLD_TYPE = "Данный тип лекарств устарел=)";
    public static final String ANTIBIOTIK = "Антибиотик";
    public static final String ANTIBIO_DESCR = "Химическое вещество, образуемое микроорганизм";
    public static final String ANTIKOGNESTAT = "Антиконгестант";
    public static final String ANTIKOGNESTAT_DESCR = "противоотечное средство, средство для снятия ";
    public static final String VITAMIN = "Витаминка";
    public static final String AMBROXOL = "Амброксол";
    public static final String AMBROXOL_IMAGE = "/home/vladislav/Online Pharmacy/out/artifacts/Online_Pharmacy_war_exploded/pictures/drugs/АмброксолlkermflekrmfАмброксол";
    public static final String IODOMARIN = "Йодомарин";
    public static final String IODOMARIN_IMAGE = "/home/vladislav/Online Pharmacy/out/artifacts/Online_Pharmacy_war_exploded/pictures/drugs/ЙодомаринlkermflekrmfЙод";
    public static final String IOD = "Йод";
    public static final String USER_LOGIN = "qweerty";
    public static final String SPECIALIZATION = "wefhoi";
    public static final String MAN_NAME = "lkermf";
    public static final String MAN_DESCRIPTION = "erklger";
    public static final String MAN_COUNTRY = "lekrmf";
    public static final String SEARCH_QUERY = "о";
    public static final String NEW_DRUG_NAME = "Аспирин";
    public static final String NEW_DRUG_DESCRIPTION = "Аспирин";
    public static final String NEW_DRUG_ACTIVE_SUBSTANCE = "Аспирин";
    public static final String NEW_DRUG_SPECIALIZATION = "Терапевт";
    public static final String RESET_QUERY = "alter table drugs auto_increment=3";
    public static final String NEW_DRUG_MANUFACTURER_NAME = "Bayer";
    public static final String NEW_DRUG_MANUFACTURER_COUNTRY = "Германия";
    public static final String NEW_DRUG_MANUFACTURER_DESCRIPTION = "Крупнейший производитель лекарств";
    public static final String MAN_NAME1 = "hahhaha";
    public static final String MAN_COUNTRY1 = "hahaha";
    public static final String MAN_DESCRIPTION1 = "hahaha";
    public static final String MAN_DESCRIPTION2 = "erlkgnelkrg";
    public static final String MAN_COUNTRY2 = "erglkneg";
    public static final String MAN_NAME2 = "nergnlk";
    public static final String MAN_NAME3 = "vla";
    public static final String MAN_COUNTRY3 = "wfkewlm";
    public static final String MAN_DESCRIPTION3 = "wefwef";
    public static final String RESET_MESSAGE_QUERY = "alter table messages auto_increment=4";
    public static final String RECEIVER_LOGIN = "shutnik";
    public static final String IGNORED_REQUEST_DATE = "requestDate";
    public static final String IGNORED_MESSAGE_STATUS = "messageStatus";
    public static final String SENDER_NAME = "qwe";
    public static final String IGNORED_DOCTOR_SPECIALIZATION = "doctorSpecialization";
    public static final String SENDER_MESSAGE = "Привет, как ты";
    public static final String SENDER_MESSAGE1 = "Агаггага";
    public static final String SENDER_MESSAGE2 = "Ну";
    public static final String RECEIVER_MESSAGE = "Ну";
    public static final String RECEIVER_MESSAGE1 = "Что ну?";
    public static final String RESET_ORDERS_QUERY = "alter table orders auto_increment=4";
    public static final String DATE_PATTERN = "yyyy-MM-dd";
    public static final String DATE = "2016-09-30";
    public static final String EXP_DATE = "2030-01-01";
    public static final String IGNORED_CLIENT = "client";
    public static final String IGNORED_SUM = "totalSum";
    public static final String IGNORED_ORDER_DATE = "orderDate";
    public static final String RESET_REQUEST = "alter table requests_for_prescriptions auto_increment=2";
    public static final String DOCTOR_LOGIN = "qaz";
    public static final String DOCTOR_FIRST_NAME = "vladislav";
    public static final String DOCTOR_SECOND_NAME = "zavadski";
    public static final String IGNORED_RESPONSE_DATE ="responseDate";
    public static final String IGNORED_PROLONG_DATE = "prolongDate";
    public static final String IGNORED_DRUG = "drug";
    public static final String IGNORED_DOCTOR = "doctor";
    public static final String IGNORED_EXPIRATION_DATE = "expirationDate";
    public static final String SECRET_RESPONSE = "qw";
    public static final String USER_MAIL = "zvg96@mail.ru";
    public static final String DOCTOR_NAME = "aaaa";
    public static final String DOCTOR_LOGIN1 = "zzpp";
    public static final String DOCTOR_PASSWORD = "qq";
    public static final String DERMATOLOG = "Дерматолог";
    public static final String NEW_LOGIN = "log";
    public static final String IGNORED_PASSWORD = "password";
    public static final String IGNORED_DESCRIPTION = "userDescription";
    public static final String NEW_NAME = "NAME";
    public static final String NEW_PASSWORD = "PASS1";
    public static final String NEW_MAIL = "MAIL";
    public static final String NEW_PHONE = "PHONE";
    public static final String NEW_IMAGE_PATH = "path";
    public static final String SOME_SPECIALIZATION = "specialization";
    public static final String SOME_DESCRIPTION = "description";
    public static final String USER_LOGIN11 = "11zavadski";
    public static final String OFT_SPECIALIZATION = "Офтальмолог";
    public static final String LOR_SPEC = "Лор";
    public static final String TERAPEVT_SPEC = "Терапевт";
    public static final String HIRURG_SPEC = "Хирург";
    public static final String END_SPEC = "Эндокринолог";
    public static final String HOW_ARE_YOU_QUESTION = "Как дела";

}
