package by.training.online_pharmacy.dao.impl.database;

import java.lang.ref.SoftReference;

/**
 * Created by vladislav on 14.07.16.
 */
public class TableColumn {
    public static final String DRUG_CLASS_NAME = "dr_class_name";
    public static final String LOGIN_VIA = "login_via";
    public static final String USER_GENDER = "us_gender";
    public static final String DRUG_CLASS_DESCRIPTION = "dr_class_description";
    public static final String DRUG_ID = "dr_id";
    public static final String DRUG_NAME = "dr_name";
    public static final String DRUG_DESCRIPTION = "dr_description";
    public static final String DRUG_PRICE = "dr_price";
    public static final String DRUG_ACTIVE_SUBSTANCE = "dr_active_substance";
    public static final String DRUG_PRESCRIPTION_ENABLE = "dr_prescription_enable";
    public static final String DRUG_IN_STOCK = "dr_in_stock";
    public static final String DRUG_TYPE = "dr_type";
    public static final String DRUG_DOSAGE = "dr_dosage";
    public static final String DRUG_MANUFACTURE_ID = "dm_id";
    public static final String DRUG_MANUFACTURE_DESCRIPTION = "dm_description";
    public static final String DRUG_MANUFACTURE_NAME = "dm_name";
    public static final String DRUG_MANUFACTURE_COUNTRY = "dm_country";
    public static final String DRUG_IMAGE = "dr_image";
    public static final String ORDER_ID = "or_id";
    public static final String ORDER_DATE = "or_date";
    public static final String USER_LOGIN = "us_login";
    public static final String USER_FIRST_NAME = "us_first_name";
    public static final String USER_SECOND_NAME = "us_second_name";
    public static final String PRESCRIPTION_APPOINTMENT_DATE = "pr_appointment_date";
    public static final String PRESCRIPTION_EXPIRATION_DATE = "pr_expiration_date";
    public static final String PRESCRIPTION_DRUG_COUNT = "pr_drug_count";
    public static final String DOCTOR_FIRST_NAME = "doc_first_name";
    public static final String DOCTOR_SECOND_NAME = "doc_second_name";
    public static final String DOCTOR_LOGIN = "doc_login";
    public static final String PRESCRIPTION_DRUG_DOSAGE = "pr_drug_dosage";
    public static final String REQUEST_ID = "re_id";
    public static final String REQUEST_STATUS = "re_status";
    public static final String REQUEST_CLIENT_COMMENT = "re_clients_comment";
    public static final String REQUEST_DOCTOR_COMMENT = "re_doctors_comment";
    public static final String REQUEST_PROLONG_TO = "re_prolong_to";
    public static final String REQUEST_DATE = "re_request_date";
    public static final String USER_GROUP = "us_group";
    public static final String USER_MAIL = "us_mail";
    public static final String USER_PHONE = "us_phone";
    public static final String USER_DESCRIPTION = "sd_description";
    public static final String USER_SPECIALIZATION = "sd_specialization";
    public static final String USER_IMAGE = "us_image";
    public static final String STAFF_USER_LOGIN = "sd_user_login";
    public static final String LOGIN_COUNT = "login_count";
    public static final String USER_PASSWORD = "us_password";
    public static final String REGISTRATION_TYPE = "login_via";
    public static final String LIMIT = "limit";
    public static final String DR_CLASS_COLUMN = "dr_class";
    public static final String MANUFACTURE = "dr_manufacturer";
    public static final String ORDER_US_LOGIN = "or_client_login";
    public static final String ORDER_LOGIN_VIA = "or_login_via";
    public static final String ORDER_DRUG_ID = "or_drug_id";
    public static final String ORDER_DRUG_COUNT  = "or_drug_count";
    public static final String ORDER_DRUG_DOSAGE = "or_drug_dosage";
    public static final String ORDER_STATUS = "or_status";
    public static final String MESSAGE_SENDER_LOGIN = "me_sender_login";
    public static final String MESSAGE_SENDER_LOGIN_VIA = "me_sender_login_via";
    public static final String MESSAGE_SENDER_MESSAGE = "me_sender_message";
    public static final String MESSAGE_RECEIVER_LOGIN = "me_receiver_login";
    public static final String MESSAGE_RECEIVER_LOGIN_VIA = "me_receiver_login_via";
    public static final String ORDER_SUM = "or_sum";
    public static final String MESSAGE_RECEIVER_MESSAGE = "me_receiver_message";
    public static final String MESSAGE_STATUS = "me_status";
    public static final String MESSAGE_REQUEST_DATE = "me_request_date";
    public static final String MESSAGE_RESPONSE_DATE = "me_response_date";
    public static final String SENDER_FIRST_NAME = "se_first_name";
    public static final String SENDER_SECOND_NAME = "se_second_name";
    public static final String RECEIVER_FIRST_NAME = "re_first_name";
    public static final String RECEIVER_SECOND_NAME = "re_second_name";
    public static final String MESSAGE_ID = "me_id";
    public static final String MESSAGE_COUNT = "me_count";
    public static final String REQUEST_DRUG_ID = "re_drug_id";
    public static final String REQUEST_DOCTOR_LOGIN = "re_doctor";
    public static final String REQUEST_DOCTOR_LOGIN_VIA = "re_doctor_login_via";
    public static final String REQUEST_DOCTOR_FIRST_NAME = "doc_first_name";
    public static final String REQUEST_DOCTOR_SECOND_NAME = "doc_second_name";
    public static final String RESPONSE_DATE=  "re_response_date";
    public static final String USER_BALANCE = "us_balance";
    public static final String QUESTION_ID = "sq_id";
    public static final String QUESTION = "sq_question";

}
