package by.training.online_pharmacy.controller;

/**
 * Created by vladislav on 18.07.16.
 */
public enum CommandName {
    USER_LOGIN, USER_REGISTRATION,
    USER_LOGIN_VK, USER_LOGIN_FB, USER_LOGIN_LI, SWITCH_LOCALE, CHECK_LOGIN, UPDATE_PERSONAL_INFORMATION, UPDATE_PASSWORD
    ,UPDATE_CONTACTS, UPLOAD_PROFILE_IMAGE, INIT_CONNECTION, DESTROY_CONNECTION, LOG_OUT, DELETE_USER, GET_ALL_DRUGS, GET_DRUGS_BY_CLASS, GET_DRUG_DETAILS, SEARCH_DRUGS
    ,EXTENDED_DRUG_SEARCH, CREATE_ORDER, CREATE_REQUEST, SEND_MESSAGE
}
